AWSTemplateFormatVersion: '2010-09-09'
Description: Create a Route 53 Hosted Zone with user-defined domain name

Parameters:
  DomainName:
    Type: String
    Description: The domain name to create the hosted zone for (e.g., example.com)

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

Outputs:
  HostedZoneId:
    Description: The ID of the created hosted zone
    Value: !Ref HostedZone

  NameServers:
    Description: Route 53 name servers to update at the domain registrar
    Value: !Join [", ", !GetAtt HostedZone.NameServers]
