AWSTemplateFormatVersion: '2010-09-09'
Description: Launch Ubuntu 24.04 EC2 instance with Nginx and custom homepage

Parameters:
  KeyPairName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP and SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  UbuntuInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyPairName
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      ImageId: ami-0e35ddab05955cf57  # Ubuntu Server 24.04 LTS (update if needed for region)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          apt update -y
          apt install nginx -y
          echo "Welcome to my Home Page" > /var/www/html/index.html
          systemctl enable nginx
          systemctl start nginx

Outputs:
  InstancePublicIP:
    Description: Public IP of the Ubuntu server
    Value: !GetAtt UbuntuInstance.PublicIp
  WebPageURL:
    Description: URL of the Nginx home page
    Value: !Sub "http://${UbuntuInstance.PublicDnsName}"
